#!/bin/sh

DAEMON="lscdoorbellmqtt"
PIDFILE="/var/run/$DAEMON.pid"
APP_PATH="/media/lscdoorbellmqtt/lscdoorbellmqtt"

# Add any additional arguments your application needs
APP_ARGS=""

start() {
    printf 'Starting %s: ' "$DAEMON"
    start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$APP_PATH" -- $APP_ARGS
    status=$?
    if [ "$status" -eq 0 ]; then
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}

stop() {
    printf 'Stopping %s: ' "$DAEMON"
    kill "$(cat $PIDFILE)"
    status=$?
    if [ "$status" -eq 0 ]; then
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "FAIL"
    fi
    return "$status"
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start|stop|restart)
        "$1"
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac